import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import openapiTS from "openapi-typescript";

const OPENAPI_URL = "http://localhost:8000/openapi.json";
const outputDir = path.resolve(process.cwd(), "src/api/generated");
const schemaPath = path.join(outputDir, "schema.ts");
const clientPath = path.join(outputDir, "client.ts");

const response = await fetch(OPENAPI_URL);
if (!response.ok) {
  throw new Error(`Failed to fetch ${OPENAPI_URL}: ${response.status} ${response.statusText}`);
}

const schema = await response.json();
const output = await openapiTS(schema);

const clientContents = `// Generated by scripts/generate-api.mjs. Do not edit manually.

import type { paths } from "./schema";
import { apiRequest } from "../client";

type HttpMethod = "get" | "post" | "put" | "delete" | "patch";

type Operation<Path extends keyof paths, Method extends HttpMethod> = Method extends keyof paths[Path]
  ? paths[Path][Method]
  : never;

type JsonResponse<Response> = Response extends { content: infer Content }
  ? Content extends { "application/json": infer Body }
    ? Body
    : Content extends { "text/plain": infer Body }
      ? Body
      : unknown
  : unknown;

type SuccessResponse<Responses> = 200 extends keyof Responses
  ? Responses[200]
  : 201 extends keyof Responses
    ? Responses[201]
    : 202 extends keyof Responses
      ? Responses[202]
      : 204 extends keyof Responses
        ? Responses[204]
        : "default" extends keyof Responses
          ? Responses["default"]
          : unknown;

export type ApiRequestBody<Path extends keyof paths, Method extends HttpMethod> = Operation<
  Path,
  Method
> extends { requestBody: { content: { "application/json": infer Body } } }
  ? Body
  : undefined;

export type ApiResponse<Path extends keyof paths, Method extends HttpMethod> = Operation<
  Path,
  Method
> extends { responses: infer Responses }
  ? JsonResponse<SuccessResponse<Responses>>
  : unknown;

export async function request<Path extends keyof paths, Method extends HttpMethod>(
  path: Path,
  method: Method,
  options: {
    body?: ApiRequestBody<Path, Method>;
  } & Omit<RequestInit, "body" | "method"> = {},
): Promise<ApiResponse<Path, Method>> {
  const { body, ...init } = options;
  return apiRequest<ApiResponse<Path, Method>>(path as string, {
    ...init,
    method: method.toUpperCase(),
    body,
  });
}
`;

await mkdir(outputDir, { recursive: true });
await writeFile(schemaPath, output);
await writeFile(clientPath, clientContents);

console.log(`Generated ${schemaPath} and ${clientPath}`);
